services:
  newsappchatbot:
    build: . # Nên giữ dòng này để nó luôn cập nhật code mới nhất Han sửa
    container_name: newsapp-chatbot
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      # Lấy giá trị từ file .env truyền vào App
      PG_DSN: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@host.docker.internal:5432/newsapp"
      BACKEND_BASE: "${BACKEND_BASE}"
      JAVA_ACCESS_TOKEN: "${JAVA_ACCESS_TOKEN}"
      GOOGLE_API_KEY: "${GOOGLE_API_KEY}"
      EMBED_PROVIDER: "${EMBED_PROVIDER}"
      EMBED_MODEL_HF: "${EMBED_MODEL_HF}"
      EMBED_DIM: "${EMBED_DIM}"
      ARTICLE_DETAIL_BASE_URL: "${ARTICLE_DETAIL_BASE_URL}"
    extra_hosts:
      - "host.docker.internal:host-gateway"
